FROM tensorflow/tensorflow:latest

ARG DEBIAN_FRONTEND=noninterctive

RUN apt-get update -y --fix-missing
RUN apt-get install -y ffmpeg
RUN apt-get install -y build-essential cmake pkg-config \
  libjpeg8-dev libtiff5-dev libpng-dev \
  libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
  libxvidcore-dev libx264-dev \
  libgtk-3-dev \
  libatlas-base-dev gfortran \
  libboost-all-dev \
  python3 python3-dev python3-numpy

RUN apt-get install -y wget python3-tk python3-pip
RUN apt-get install -y unzip

WORKDIR /

RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.4.0.zip \
  && unzip opencv.zip \
  && wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.4.0.zip \
  && unzip opencv_contrib.zip

RUN cd /opencv-4.4.0/ \
  && mkdir build \
  && cd build \
  && cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D INSTALL_C_EXAMPLES=OFF \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=/opencv_contrib-4.4.0/modules \
    -D BUILD_EXAMPLES=OFF \
    -D BUILD_opencv_python2=OFF \
    -D BUILD_NEW_PYTHON_SUPPORT=ON \
    -D CMAKE_INSTALL_PREFIX=$(python3 -c "import sys; print(sys.prefix)") \
    -D PYTHON_EXECUTABLE=$(which python3) \
    -D WITH_FFMPEG=1 \
    -D WITH_CUDA=0 \
    -D WITH_JASPER=ON \
    .. \
  && make -j8 \
  && make install \
  && ldconfig \
  && rm /opencv.zip \
  && rm /opencv_contrib.zip

RUN wget -O dlib-19.21.tar.bz2 http://dlib.net/files/dlib-19.21.tar.bz2 \
  && tar -vxjf dlib-19.21.tar.bz2

RUN cd dlib-19.21 \
  && cd examples \
  && mkdir build \
  && cd build \
  && cmake ..\
  && cmake --build . --config Release \
  && cd /dlib-19.21 \
  && pip3 install setuptools \
  && python3 setup.py install \
  && cd $WORKDIR \
  && rm /dlib-19.21.tar.bz2

ADD $PWD/requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

CMD ["/bin/bash"]
